# Generated by Django 4.1.3 on 2022-12-03 18:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='balance_is_not_negative',
        ),
        migrations.RemoveConstraint(
            model_name='card',
            name='series_number_unique_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='zero_amount_transaction',
        ),
        migrations.RemoveField(
            model_name='card',
            name='number',
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', Decimal('0'))), name='negative_card_balance_disallowed'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount', Decimal('0')), _negated=True), name='zero_amount_transaction_disallowed'),
        ),
    ]
