# Generated by Django 4.1.3 on 2022-12-06 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardseries',
            name='duration_type',
        ),
        migrations.AddField(
            model_name='cardseries',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(days=30), 'One month'), (datetime.timedelta(days=183), 'Six month'), (datetime.timedelta(days=365), 'One year')], default=datetime.timedelta(days=30), help_text='Card duration type', verbose_name='card_duration_type'),
        ),
    ]
