# Generated by Django 4.1.3 on 2022-12-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_balance_is_not_negative_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_duration_type',
            new_name='duration_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is card active?', verbose_name='is_active'),
        ),
    ]
